version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"   
    networks:
      - my-network
    depends_on:
      - backend
      - db

  backend:
    build: ./backend
    ports:
      - "8000:8000"  
    networks:
      - my-network
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: library_management
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # Mount the directory containing SQL files
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
